name: check

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0

      - name: Install, test and build
        uses: actions/setup-node@v1
        with:
          node-version: 16.15.0
      - run: bun install
      - run: bun test
      - run: bun run build
